### ISSUE TITLE
some mistakes happen when i run your code.

### ISSUE THREAD

**Issue by smallzxy** [yuanxiaosc/Entity-Relation-Extraction#2]
some mistakes happen when run eval, can you help me?

here are the details:
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "run_predicate_classification.py", line 812, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_predicate_classification.py", line 741, in main
    result = estimator.evaluate(input_fn=eval_input_fn, steps=eval_steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2424, in evaluate
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2418, in evaluate
    name=name
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 478, in evaluate
    return _evaluate()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 460, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1484, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1520, in _call_model_fn_eval
    features, labels, model_fn_lib.ModeKeys.EVAL, config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2195, in _call_model_fn
    features, labels, mode, config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2479, in _model_fn
    features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1259, in call_without_tpu
    return self._call_model_fn(features, labels, is_export_mode=is_export_mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1538, in _call_model_fn
    return estimator_spec.as_estimator_spec()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 330, in as_estimator_spec
    prediction_hooks=self.prediction_hooks + hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/model_fn.py", line 236, in __new__
    'tuples, given: {} for key: {}'.format(value, key))
TypeError: Values of eval_metric_ops must be (metric_value, update_op) tuples, given: Tensor("Abs:0", shape=(), dtype=float32) for key: eval_accuracy

**Comment by yuanxiaosc** [comment]
那是因为关于验证集的代码没有写完毕，可以先关闭验证功能--do_train=true \
--do_eval=false 然后直接使用模型预测，可以把预测结果用Entity-Relation-Extraction/bin/evaluation/中的脚本评测。本模型的在没有调参的情况下可以达到80F1分数。

**Comment by smallzxy** [comment]
ok. Thanks for your apply!
