### ISSUE TITLE
No such file or directory: 'bin/subject_object_labeling/sequence_labeling_data/test/token_in_and_one_predicate.txt'

### ISSUE THREAD

**Issue by mymusise** [yuanxiaosc/Entity-Relation-Extraction#38]
进行 序列标注模型预测 时候出现Error
```bash
python run_sequnce_labeling.py \
  --task_name=SKE_2019 \
  --do_predict=true \
  --data_dir=bin/subject_object_labeling/sequence_labeling_data \
  --vocab_file=pretrained_model/chinese_L-12_H-768_A-12/vocab.txt \
  --bert_config_file=pretrained_model/chinese_L-12_H-768_A-12/bert_config.json \
  --init_checkpoint=output/sequnce_labeling_model/epochs9/model.ckpt-22000 \
  --max_seq_length=128 \
  --output_dir=./output/sequnce_infer_out/epochs9/ckpt22000
```
Exception:
```
W0202 13:40:21.592350 139693254723392 tpu_context.py:222] eval_on_tpu ignored because use_tpu is False.
Traceback (most recent call last):
  File "run_sequnce_labeling.py", line 885, in <module>
    tf.app.run()
  File "/srv/jupyterhub/envs/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/srv/jupyterhub/envs/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/srv/jupyterhub/envs/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_sequnce_labeling.py", line 826, in main
    predict_examples = processor.get_test_examples(FLAGS.data_dir)
  File "run_sequnce_labeling.py", line 235, in get_test_examples
    with open(os.path.join(data_dir, os.path.join("test", "token_in_and_one_predicate.txt")), encoding='utf-8') as token_in_f:
FileNotFoundError: [Errno 2] No such file or directory: 'bin/subject_object_labeling/sequence_labeling_data/test/token_in_and_one_predicate.txt'
```

看了下 `bin/subject_object_labeling/sequence_labeling_data/test/` 目录是空的

另外：`bin/prepare_data_for_labeling_infer.py` 好像没有这个脚本。

**Comment by mymusise** [comment]
脚本路径迁移到 `bin/predicate_classifiction/prepare_data_for_labeling_infer.py` 了，重新执行脚本后 再运行 `run_sequnce_labeling.py` 就OK了
