### ISSUE TITLE
运行 run_predicate_classification.py 中出现keyError

### ISSUE THREAD

**Issue by liuxz-cs** [yuanxiaosc/Entity-Relation-Extraction#43]
你好，我按照ReadMe.md中的方式运行run_predicate_classification.py，出现如下的错误：

Traceback (most recent call last):
  File "run_predicate_classification.py", line 821, in <module>
    tf.app.run()
  File "/data/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_predicate_classification.py", line 698, in main
    train_examples, label_list, FLAGS.max_seq_length, tokenizer, train_file)
  File "run_predicate_classification.py", line 385, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "run_predicate_classification.py", line 347, in convert_single_example
    label_ids = _predicate_label_to_id(label_list, label_map)
  File "run_predicate_classification.py", line 371, in _predicate_label_to_id
    predicate_label_ids[predicate_label_map[label]] = 1
KeyError: ''

不知道这个问题应该如何解决

**Comment by yuanxiaosc** [comment]
不知道你是用的该比赛的数据还是自己的数据，如果是自己的数据肯定会出现该错误，因为在run_predicate_classification.py文件的238行-242行已经将预定义的标签写死了，你需要根据自己的数据集的标签改写这部分内容。

**Comment by liuxz-cs** [comment]
是用的比赛数据集
